# Form implementation generated from reading ui file 'start_window.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(554, 313)
        self.login_button = QtWidgets.QPushButton(parent=Form)
        self.login_button.setGeometry(QtCore.QRect(380, 140, 121, 41))
        self.login_button.setObjectName("login_button")
        self.new_user_button = QtWidgets.QPushButton(parent=Form)
        self.new_user_button.setGeometry(QtCore.QRect(380, 210, 121, 41))
        self.new_user_button.setObjectName("new_user_button")
        self.webcam_label = QtWidgets.QLabel(parent=Form)
        self.webcam_label.setGeometry(QtCore.QRect(30, 30, 311, 251))
        self.webcam_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.webcam_label.setObjectName("webcam_label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.login_button.setText(_translate("Form", "Login"))
        self.new_user_button.setText(_translate("Form", "Register New User"))
        self.webcam_label.setText(_translate("Form", "Webcam feed..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
